### PR TITLE
Separate certificate handling from cluster start

### PR DESCRIPTION
**Pull request by benesch**
And various other goodies.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/206)

### CODE REVIEW

**Review by petermattis — APPROVED** [review]
:lgtm:

Curious about the motivation for `distribute-certs` and `wipe --preserve-certs`.

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/206#-:-LNLzkM4EARcYlAaDulr:b-ukcn2p)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @petermattis and @benesch)

___
*[install/cluster_synced.go, line 682 at r3](https://reviewable.io/reviews/cockroachdb/roachprod/206#-LNLzYow8Cw6evRhTmfW:-LNLzYow8Cw6evRhTmfX:be87o53) ([raw file](https://github.com/cockroachdb/roachprod/blob/a1be57948ec09004cc2a55f5a2d50150f0f819f8/install/cluster_synced.go#L682)):*
> ```Go
> 		})
> 	}
> }
> ```

I take it this is all code movement.

**Review by petermattis — APPROVED** [review]
Still looks good to me.

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/206#-:-LNN-KxI3WaGqQhVu0Lo:b-lpkcc5)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @petermattis and @benesch)

**Comment by benesch** [comment]
Ok, great. I’ll send you the reason for all these changes (a PR in the main
repo that updates to the rapid restart test so it’s capable of reproing
that admin UI startup panic) before I merge this. I might yet need some
more support from roachprod.

**Comment by andreimatei** [comment]
roachprod has moved to the main repo

**Comment by kenliu** [comment]
@ajwerner could you eyeball this PR and see if it can be merged into main `cockroach` repo? Would like to close out this PR if possible.

**Comment by ajwerner** [comment]
This repo is no longer in use. Roachprod has been moved into the cockroach repo. See pkg/come/roachprod

**Comment by ajwerner** [comment]
Yes, I’ll take a look

**Comment by kenliu** [comment]
closing this out since it has been handled in the cockroach repo

**Pull request closed without merging**
