### PR TITLE
roachprod: add eu-west-2 AWS zone to roachprod

### PR DESCRIPTION
**Pull request by m-schneider**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/241)

### CODE REVIEW

**Review by bobvawter — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/241#-:-LROK-sy1KK_a1lj2gva:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @bobvawter)

**Review by bobvawter — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/241)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by petermattis** [comment]
roachprod recently moved to the main cockroach repo.

**Review by m-schneider — COMMENTED** [review]
Moved.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/241#-:-LROTIqE6Gi022ceHDsf:bwhglds)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request closed without merging**
