### PR TITLE
roachprod: change kv test to use workload

### PR DESCRIPTION
**Pull request by m-schneider**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/188)

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/188)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @m-schneider and @nvanbenschoten)

___
*[tests.go, line 402 at r1](https://reviewable.io/reviews/cockroachdb/roachprod/188#-LKwV9Sc5Wd9qcNEuu19:-LKwV9Sd6rI1Q4hPJU1N:b10rsyb) ([raw file](https://github.com/cockroachdb/roachprod/blob/a459a57ad0d3ccd03994ea1d35b46b47235e17f5/tests.go#L402)):*
> ```Go
> 
> func kv95(clusterName, dir string) {
> 	kvTest(clusterName, "kv_95", dir, "./workload run kv --init --read-percent=95 --splits=1000")
> ```

Nice! If we're going to do this though, we should for all of these tests.

Also, @petermattis might want to take a look.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/188)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @m-schneider)

___
*[tests.go, line 402 at r1](https://reviewable.io/reviews/cockroachdb/roachprod/188#-LKwV9Sc5Wd9qcNEuu19:-LKwVpth3hdT1j6yKkPO:bptlxhe) ([raw file](https://github.com/cockroachdb/roachprod/blob/a459a57ad0d3ccd03994ea1d35b46b47235e17f5/tests.go#L402)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Nice! If we're going to do this though, we should for all of these tests.

Also, @petermattis might want to take a look.
</blockquote></details>

I'm really hoping to get rid of `roachprod test` soon. This functionality belongs in `roachtest`. With subtests, it doesn't seem difficult to add. Perhaps a `roachtest bench`.

**Comment by m-schneider** [comment]
___
*[tests.go, line 402 at r1](https://reviewable.io/reviews/cockroachdb/roachprod/188#-LKwV9Sc5Wd9qcNEuu19:-LKwwa0T9xfIoWhuIj2u:b-jfxob5) ([raw file](https://github.com/cockroachdb/roachprod/blob/a459a57ad0d3ccd03994ea1d35b46b47235e17f5/tests.go#L402)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm really hoping to get rid of `roachprod test` soon. This functionality belongs in `roachtest`. With subtests, it doesn't seem difficult to add. Perhaps a `roachtest bench`.
</blockquote></details>

Should I also move the graph generator code?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/188)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @nvanbenschoten)

___
*[tests.go, line 402 at r1](https://reviewable.io/reviews/cockroachdb/roachprod/188#-LKwV9Sc5Wd9qcNEuu19:-LKwx27WAPgoTr8717r7:bqra1y) ([raw file](https://github.com/cockroachdb/roachprod/blob/a459a57ad0d3ccd03994ea1d35b46b47235e17f5/tests.go#L402)):*
<details><summary><i>Previously, m-schneider (Masha Schneider) wrote…</i></summary><blockquote>

Should I also move the graph generator code?
</blockquote></details>

Probably not. It is very specific to the output here. My vision is that graphing stuff gets replaced with something that processes the workload json histograms.

**Comment by andreimatei** [comment]
roachprod has moved into the main repo. Pls close this.

**Comment by m-schneider** [comment]
I don't think we're going forward with this, closing.

**Pull request closed without merging**
