### PR TITLE
Update ubuntu OS image to version that includes meltdown/spectre fixes

### PR DESCRIPTION
**Pull request by a-robinson**
@jordanlewis you mentioned that you'd test tpc-c performance before/after this change, but let me know if you need me to.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/roachprod/137)

### CODE REVIEW

**Comment by bdarnell** [comment]
Ping.

**Comment by jordanlewis** [comment]
Totally let this slip. Can you show me how to launch a cluster with this image? I'll test it today.

**Comment by a-robinson** [comment]
Patch this one line change into your local checkout of the repo, run `go install github.com/cockroachdb/roachprod` to build and install your locally modified repo, then use roachprod as you would normally.

**Comment by jordanlewis** [comment]
The latencies for TPCC-1000 seem to be repeatably about 10% worse than on the old image. Is that enough information, and does that square with your observations?

**Comment by a-robinson** [comment]
I didn't see any noticeable differences when running some simple benchmarks with kv, but 10% worse sounds believable.

In that case, maybe we want to hold off on this.

**Comment by andreimatei** [comment]
roachprod has moved into the main repo. Pls close this.

**Pull request closed without merging**
